CREATE TABLE [dbo].[Order]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY, 
    [CustomerId] BIGINT NOT NULL, 
    [OrderNumber] VARCHAR(16) NULL, 
    [Total] DECIMAL(10, 2) NULL, 
    [Status] VARCHAR(16) NOT NULL, 
    [CreateDate] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(), 
    [UpdatedDate] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET()
)